version: '3.6'

services:
  bot:
    # image: php:7.3-apache
    build: build/.
    volumes:
      - ./volumes/log:/var/log
      - ./web:/var/www/html
    restart: always
    ports:
      - "9000:80"
